### ISSUE TITLE
이거 어떻게 실행하나요?

### ISSUE THREAD

**Issue by comjun04** [PMHStudio/KoreanScript#2]
무조건 다운받아서 실행해야 하나요?

아니면 온라인 실행 방법을 `README.md`에 올려주세요

**Comment by pmh-only** [comment]
예 다운받아서 실행해야 합니다
그러나, 제한된 기능을 가진 웹버전: http://kost.pmhstudio.kro.kr 를 사용하실 수 도 있습니다
